const data = {
  products: [
    {
      //_id: '1',
      name: 'Oreo Biscuits',
      slug: 'oreo-buiscuits',
      category: 'Bakery',
      image: '/images/p1.jpg',
      price: 60,
      countInStock: 10,
      brand: 'Oreo',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality biscuits',
    },
    {
      // _id: '2',
      name: 'Tata Salt',
      slug: 'tata-salt',
      category: 'Stationary',
      image: '/images/p2.jpg',
      price: 40,
      countInStock: 5,
      brand: 'Tata',
      rating: 4.5,
      numReviews: 12,
      description: 'high quality product',
    },
    {
      //_id: '3',
      name: 'Peanut Butter',
      slug: 'peanut-butter',
      category: 'Bakery',
      image: '/images/p3.jpg',
      price: 100,
      countInStock: 0,
      brand: 'Butter',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
};
export default data;
